// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Clear

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture3D<unorm float> SdfVolumeTexture;

float sphereDistance(float3 samplePoint, float radius)
{
    return length(samplePoint) - radius;
}

[numthreads(8,8,8)]
void Clear (uint3 id : SV_DispatchThreadID)
{
    SdfVolumeTexture[id.xyz] = sphereDistance((id.xyz / 63.0) - 0.5, 0.45) * 0.5 + 0.5;
}
